"""initial migration

Revision ID: e66ffe2e8312
Revises: 
Create Date: 2021-03-01 05:54:12.629861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66ffe2e8312'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fr', 'admin1_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'admin2_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'admin3_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'admin4_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'alternatenames',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'asciiname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'cc2',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'country_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'dem',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'elevation',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'feature_class',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'feature_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'latitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'longitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'modification_date',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'population',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('fr', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('fr', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'population',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'modification_date',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'longitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'latitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'feature_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'feature_class',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'elevation',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'dem',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'country_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'cc2',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'asciiname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'alternatenames',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'admin4_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'admin3_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'admin2_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('fr', 'admin1_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
